version: 0.2
phases:
    install:
        runtime-version:
            dotnet: 6.0
    pre_build:
        commands:
            - echo Restore started on `date`
            - dotnet restore WorkerServiceCodeDeploy.csproj
    build:
        commands:
            - echo Build started on `date`
            - dotnet publish -c release -o ./build_output WorkerServiceCodeDeploy.csproj
artifacts:
    files:
        - build_output/**/*
        - deploy-scripts/**/*
        - appspec.yml
        